version: '3.3'
services:
  web1:
    image: mlucas/php:7.2-apache-redis
    build:
      context: buildfiles/web
      dockerfile: Dockerfile-php-7.2
    container_name: devweb1
    ports:
      - "8080:80"
    links:
      - redis:devcache1
    volumes:
      - ./web/html:/var/www/html
  web2:
    image: mlucas/php:7.2-apache-redis
    container_name: devweb2
    ports:
      - "8180:80"
    links:
      - redis:devcache1
    volumes:
      - ./web/html:/var/www/html
  web3:
    image: mlucas/php:7.2-apache-redis
    container_name: devweb3
    ports:
      - "8280:80"
    links:
      - redis:devcache1
    volumes:
      - ./web/html:/var/www/html
  redis:
    image: redis:4.0.11-alpine
    #build: buildfiles/cache
    container_name: devcache1
    volumes:
       - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf


